databases:
  - name: save-point
    databaseName: save point
    user: save point

services:
  - type: web
    name: save-point
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: save-point
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
